language: python
pythonVersion: '3.12'
startupCommand: gunicorn --bind=0.0.0.0:$PORT --timeout 600 --workers 1 --access-logfile - --error-logfile - app:app
buildCommands:
  - pip install -r requirements.txt
  - python -c "import app; print('Application validation successful')"

# Azure Web App specific settings
appSettings:
  - name: FLASK_ENV
    value: staging
  - name: WEBSITE_NODE_DEFAULT_VERSION
    value: ~18
  - name: SCM_DO_BUILD_DURING_DEPLOYMENT
    value: true
  - name: ENABLE_ORYX_BUILD
    value: true
  - name: PYTHON_ENABLE_VENV_CREATION
    value: true
  - name: PYTHON_ENABLE_VENV_CREATION_DURING_DEPLOYMENT
    value: true

# Health check configuration
healthCheckPath: /health
healthCheckEvictionTime: 2m

# Logging configuration
applicationLogs:
  fileSystem:
    level: information
  azureBlobStorage:
    level: information
    sasUrl: "https://netrunlogs.blob.core.windows.net/logs?sv=2020-08-04&ss=b&srt=sco&sp=rwdlacx&se=2024-12-31T23:59:59Z&st=2024-01-01T00:00:00Z&spr=https&sig=YOUR_SAS_TOKEN"

# Monitoring configuration
monitoring:
  applicationInsights:
    connectionString: "YOUR_APPINSIGHTS_CONNECTION_STRING"
  openTelemetry:
    enabled: true
    samplingRate: 1.0

# Security configuration
security:
  cors:
    allowedOrigins:
      - https://*.netrunsystems.com
      - https://*.azurewebsites.net
  authentication:
    enabled: true
    defaultProvider: "azureActiveDirectory"
  headers:
    xFrameOptions: "SAMEORIGIN"
    xContentTypeOptions: "nosniff"
    xXSSProtection: "1; mode=block"
    strictTransportSecurity: "max-age=31536000; includeSubDomains" 